apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-git-guestbook-staging
spec:
  project: default
  source:
    repoURL: https://github.com/bboykov/guestbook
    path: deployments/helm-guestbook
    targetRevision: HEAD
    helm:
      releaseName: helm-git-guestbook-staging
      version: v3
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    namespace: helm-git-guestbook-staging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
