---
apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  name: github-bboykov-pat-repos-creds
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
