apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: kube-prometheus-stack-helm-repo
  namespace: argocd
type: Opaque
stringData:
  name: kube-prometheus-stack
  project: default
  type: helm
  url: https://prometheus-community.github.io/helm-charts
