apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base/
- github-bboykov-pat-repos-creds-secret.yaml
- kube-prometheus-stack-helm-repo.yaml


# Generate secrets from <name>_secrets.env, appending the Base64-encoded values
# to the Secrets definition at the time of kustomize build
secretGenerator:
  - behavior: merge
    name: github-bboykov-pat-repos-creds
    namespace: argocd
    type: Opaque
    envs:
      - bboykov-repos-creds-secrets.env
