apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-repo-nginx-staging
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 15.3.4
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: service.type
          value: ClusterIP
        - name: replicaCount
          value: '3'
    chart: nginx
  destination:
    namespace: helm-repo-nginx-staging
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
