---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    helm:
      releaseName: argocd
      valueFiles:
      - $values/cicd/argocd/deployments/helm/overrides/argocd.yaml
    targetRevision: 5.46.8
  - repoURL: https://github.com/bboykov/kubernetes-lab.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
